name: ntf
channels:
  - conda-forge
  - defaults
dependencies:
  - dash==1.4.1
  - dash-core-components==1.3.1
  - dash-daq==0.2.1
  - dash-html-components==1.0.1
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - plotly=4.2.1
  - pytest
  - python=3.7.3